### ISSUE TITLE
Minor corrections to readme regarding Binaryen

### ISSUE THREAD

**Issue by kripken** [cfallin/waffle#10]
The readme mentions this:

> Binaryen is able to stackify/reloop arbitrary control flow (CFG to Wasm) but does not implement the other direction (Wasm to CFG)

Binaryen does actually have wasm to CFG utilitites. In particular [cfg-traversal](https://github.com/WebAssembly/binaryen/blob/main/src/cfg/cfg-traversal.h) builds up a CFG, on top of which we build liveness analyses and other things, which are used by many passes (see also the higher-level [cfg.h](https://github.com/WebAssembly/binaryen/blob/main/src/analysis/cfg.h)). There is also the [ReReloop pass](https://github.com/WebAssembly/binaryen/blob/main/src/passes/ReReloop.cpp) which converts wasm to a CFG, optimizes the shape of the CFG, and converts back.

Another minor point from the readme:

> and [Binaryen] has only a C/C++ API, not Rust.

Not in the core repo, yeah. But there are a few bindings for Binaryen to Rust, see

* https://github.com/w3f/Grants-Program/blob/master/applications/wasm-opt-for-rust.md (which was completed)
* https://github.com/pepyakin/binaryen-rs

**Comment by cfallin** [comment]
Just updated, thanks!
